### ISSUE TITLE
terrakube default values should work out of the box

### ISSUE THREAD

**Issue by Diliz** [AzBuilder/terrakube-helm-chart#46]
Hello there!

The helm chart should be installable as it is in a simple kubernetes environment, like minikube, kind, or whatever clusters.

It would provide a better "accessibility" to this tool, and facilitate adoption,  I currently had to check the templates and values.schema.json to make it work, should not really be the case for "default" kubernetes context (like quick homelabs stuff)

Can you provide a "sandbox" version of the values that would work just by using helm install as this?

EDIT:

By doing:
```sh
helm repo add terrakube-community https://AzBuilder.github.io/terrakube-helm-chart
helm repo update
helm install terrakube-community/terrakube -n terrakube --generate-name
```
I got the following output:
```sh
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
terrakube:
- ui.serviceType: ui.serviceType must be one of the following: "ClusterIP", "NodePort", "LoadBalancer", "ExternalName"
- ingress.ui.pathType: ingress.ui.pathType must be one of the following: "ImplementationSpecific", "Exact", "Prefix"
- ingress.api.pathType: ingress.api.pathType must be one of the following: "ImplementationSpecific", "Exact", "Prefix"
- ingress.registry.pathType: ingress.registry.pathType must be one of the following: "ImplementationSpecific", "Exact", "Prefix"
- registry.serviceType: registry.serviceType must be one of the following: "ClusterIP", "NodePort", "LoadBalancer", "ExternalName"
- security: patSecret is required
- security: internalSecret is required
- api.properties.databaseType: api.properties.databaseType must be one of the following: "H2", "SQL_AZURE", "POSTGRESQL", "MYSQL"
- api.serviceType: api.serviceType must be one of the following: "ClusterIP", "NodePort", "LoadBalancer", "ExternalName"
- executor.serviceType: executor.serviceType must be one of the following: "ClusterIP", "NodePort", "LoadBalancer", "ExternalName"
```

**Comment by alfespa17** [comment]
Hello @Diliz 

I understand your point that is something that we need to improve in the helm chart. 

We have been thinking how to do acomplish this when installing for example in minikube with some default values but rigth now I am not really sure how to do it because of the following:

* Dex configuration (this needs external dependency like ldap, azure ad, google identity, etc) to make it work.

Any suggestion of how we can accomplish this is welcome.

This is why we provide several examples in inside this [folder](https://github.com/AzBuilder/terrakube-helm-chart/tree/main/examples) , there you can find examples for the values that you will need when installing with different cloud providers:

Google Identity Authentication
[Ngnix Ingress + H2 Database + GCP Storage Bucket](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/GoogleAuthentication-Example1.md)
[Ngnix Ingress + PostgreSQL + GCP Storage Bucket](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/GoogleAuthentication-Example3.md)
[Ngnix Ingress + MySQL + GCP Storage Bucket](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/GoogleAuthentication-Example3.md)
Azure Authentication
[Ngnix Ingress + H2 Database + Azure Storage Account](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/AzureAuthentication-Example1.md)
[Ngnix Ingress + SQL Azure + Azure Storage Account](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/AzureAuthentication-Example2.md)
[Ngnix Ingress + PostgreSQL + Azure Storage Account](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/AzureAuthentication-Example3.md)
[Amazon Load Balancer + PostgreSQL + S3 Bucket](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/AzureAuthentication-Example4.md)
Github Authentication
[Ngnix Ingress + H2 Database + Azure Storage Account](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/GithubAuthentication-Example1.md)
Amazon AWS Cognito
[Ngnix Ingress + H2 Database + AWS S3 Bucket](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/CognitoAuthentication-Example1.md)

**Comment by Diliz** [comment]
Hello!

Yep, I was more thinking about maybe having a user password authentication without a dex thing per default so you could use it everywhere

And I'm wondering why the official dex chart was not used here? (https://github.com/dexidp/helm-charts)

**Comment by alfespa17** [comment]
Hello.

Local accounts coud be a good idea this will help so we can deploy the helm chart without any external dependency. 

Maybe this could be implemented using the [spring-authorization-server](https://github.com/spring-projects/spring-authorization-server) it implement OIDC so we could basically just put DEX on top and have something like local accounts, we will have to do some research to add a feature like this one. I will create an issue around this in our main repository

For your question about the dex helm chart,  well we tried to keep it simple so we just add a very basic dex implementation.

**Comment by Diliz** [comment]
Re!

Had some ideas on how to do that, related to https://github.com/AzBuilder/terrakube/issues/329
There should be 2 things here to make it "installable" locally without too much to do I think:
- add local/private storage/databases values in here as well (same as https://github.com/AzBuilder/terrakube/issues/329)
- more an advice than else, use third party helm charts when you can, like minio, dex, and postgres ones at least, so you just have to maintain your application values and stuff in the beginning

I'll try to provide you a simple openshift values (doing openshift here + s3 operator as an example), but I'm struggling with bad user rights in the ui pod right now.

Your chart should always be launchable in sandboxed mode from my point of view, from an active developper or as a newcomer, if the user is struggling to make your product work, he will lose faith in your product

(I'll try to help on this chart because I think this is a good product, just need some "helm install . and everything's running" magic here)

**Comment by alfespa17** [comment]
I opened this issue to explore options for a future implementation of [local accounts](https://github.com/AzBuilder/terrakube/issues/330). 

All help  is welcome 👍 if you want to contribute with some example or enhancements feel free to send a pull request.

**Comment by alfespa17** [comment]
By the way after I saw you comment about the user righst in the UI pod I noticed the image was using a "root" user, I did a small update in the Dockerfile using the bitnami/nginx image and now the image is not running as root anymore, you could check terrakube version 2.11.2 with the helm chart 2.3.1 maybe that help with your issue with bad user rigths.

**Comment by Diliz** [comment]
As a Quick win, using keycloak + dex on minikube should work for you hère, I'll try that on my side, still need the ability to declare the local storage/dex stuff in the chart without using kustomize (which I did to override the application properties given to the apps

Thanks for the nginx image, I'll check this out

**Comment by alfespa17** [comment]
Let me check the helm chart I will make it work with minikube, I will do the changes so you dont need to add the database configuration or the storage part I think I can make it work with MINIO like we do in GITPOD.

For the UI error, make sure you are using the latest version 2.11.2 and the helm chat 2.3.1.

```
## UI Properties
ui:
  enabled: true
  version: "2.11.2"
  replicaCount: "1"
  serviceType: "ClusterIP"
```
You should see a file /app/env-config.js with the information like this if the UI setup was done correctly.
![image](https://user-images.githubusercontent.com/4461895/221588272-dfe82e7e-f522-4201-a9e8-031686c130cc.png).

![image](https://user-images.githubusercontent.com/4461895/221590366-a15018da-94ac-4d01-9675-88d5c040b4f4.png)

I never noticed the duplicated secret I will fix that in the registry secret thank you.

Not sure about the executor error I guess is related to the helm chart values. that you are using maybe the storage configuration.  Maybe you can share the storage part of the helm chart that you are using and the executor properties.

It will be something like this if you are using minio:

```
storage:
  aws:
    accessKey: ""
    secretKey: ""
    bucketName: ""
    region: ""
    endpoint: ""
```

```
## Executor properties
executor:
  enabled: true
  version: "2.11.2"  
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    toolsRepository: "https://github.com/AzBuilder/terrakube-extensions"
    toolsBranch: "main"
```

**Comment by alfespa17** [comment]
Now you should be able to use minikube @Diliz .

Please check this PR for more information https://github.com/AzBuilder/terrakube-helm-chart/pull/49/

I tested minikube in Ubuntu and it should work.

![image](https://user-images.githubusercontent.com/4461895/221750193-e938a33a-15be-4063-85ac-42f32d73ef58.png)

**Comment by alfespa17** [comment]
By the way I used openldap for the default user and groups because I used the same approach in GITPOD, I am not really familiar with keycloak so I was not sure how to implemement it with minikube but if you have any suggestion let me know so I can learn a little bit about that.

**Comment by alfespa17** [comment]
Added some documentation here

https://docs.terrakube.org/getting-started/deployment/minikube

**Comment by Diliz** [comment]
Oh nice! Didn't saw your comment before! I'll try that, thank you for the work :)

**Comment by alfespa17** [comment]
Hello @Diliz  the openldap wont work because the container is running as root (I will change that later but for now it will work for minikube for a quick sandbox to test terrakube)

Just disable the openLDAP using the following:

```
security:
  useOpenLDAP: false
```

You will have to add your DEX configuration, now it is using the official helm chart, you can read a little in this doc.

https://docs.terrakube.org/getting-started/deployment/user-authentication-dex

For the error in your executor component, I think is failing right here.

```bash
Caused by: java.lang.RuntimeException: Error creating TerraformDownloader
	at org.terrakube.terraform.TerraformDownloader.<init>(TerraformDownloader.java:44)
	at org.terrakube.terraform.TerraformClient.<init>(TerraformClient.java:33)
	at org.terrakube.terraform.TerraformClient$TerraformClientBuilder.build(TerraformClient.java:12)
	at org.terrakube.terraform.spring.autoconfigure.TerraformAutoConfiguration.terraformClient(TerraformAutoConfiguration.java:19)
```

https://github.com/AzBuilder/terraform-spring-boot/blob/master/terraform-client/src/main/java/org/terrakube/terraform/TerraformDownloader.java#L44

Internally it is calling this hashicorp endpoint to downlod the list of available terraform versions with this URL

https://releases.hashicorp.com/terraform/index.json

Maybe you can check if you are able to call that endpoint because it is just downloading a json file here.

https://github.com/AzBuilder/terraform-spring-boot/blob/master/terraform-client/src/main/java/org/terrakube/terraform/TerraformDownloader.java#L99

Maybe some proxy setting but not sure.

**Comment by Diliz** [comment]
> Internally it is calling this hashicorp endpoint to downlod the list of available terraform versions with this URL

Ah! That should be the issue! For private kubernetes clusters (air gapped ones), I'll try to mock the call so it would work without connecting to internet at all, but can be good to be able to at least provide a private registry or this index.json file (I'll check what kind of registry it is after mocking it)

Thanks for your answers/work here, it's been helping greatly!

**Comment by alfespa17** [comment]
I will add support to have a custom index.json it is very easy to implement. It wont require a lot of time and It will be need it for private cluster because terrakube download the terraform binary from hashicorp url.

If I add support for that URL  you can even compile your custom terraform cli and use it inside the platform

**Comment by alfespa17** [comment]
Hello @Diliz I did the quick fix to support a custom terraform releases url.

> I will release this in terrakube 2.12.0 later this month but for now you could test it.

Try adding this to your values.yaml when deploying the helm chart

```yaml
api:
  version: "2.12.0-beta.1"
  terraformReleasesUrl: "https://eov1ys4sxa1bfy9.m.pipedream.net/"

executor:
  version: "2.12.0-beta.1"
```

> terraformReleasesUrl should be your internal endpoint

You will have to expose GET request with the following structure:

```json
{
   "name":"terraform",
   "versions":{
      "1.3.9":{
         "builds":[
            {
               "arch":"amd64",
               "filename":"terraform_1.3.9_linux_amd64.zip",
               "name":"terraform",
               "os":"linux",
               "url":"https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip",
               "version":"1.3.9"
            }
         ],
         "name":"terraform",
         "shasums":"terraform_1.3.9_SHA256SUMS",
         "shasums_signature":"terraform_1.3.9_SHA256SUMS.sig",
         "shasums_signatures":[
            "terraform_1.3.9_SHA256SUMS.72D7468F.sig",
            "terraform_1.3.9_SHA256SUMS.sig"
         ],
         "version":"1.3.9"
      }
   }
}
```
You can change this field to any internal storage URL so terrrakube can download the terraform cli from a custom location

```
"url":"https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip",
``` 

You could even use this to build a cutom terraform cli version or restrict the terraform version available in the UI.

Example:
![image](https://user-images.githubusercontent.com/4461895/223222015-4728843b-f5e7-4672-a19f-212300563df9.png)


When running executore should look like this:
```
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl - Running Terraform show
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformClient - Creating terraform downloader using custom terraform release URL: https://releases.hashicorp.com/terraform/index.json
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Initialize TerraformDownloader using custom URL

**Comment by alfespa17** [comment]
I think you can add this web.allowedOrigins to your dex config:

Example: 
```
    config:
      issuer: https://terrakube-api.minikube.net/dex
      storage:
        type: memory
      oauth2:
        responseTypes: ["code", "token", "id_token"] 
        skipApprovalScreen: true
      web:
        allowedOrigins: ['*']
```

**Comment by Diliz** [comment]
Hello again! Yep I already did this, and it's working, have cors issues when contacting the terrakube api from the terrakube ui now, do you know where I can put custom certs to allow them to talk to each other?

**Comment by alfespa17** [comment]
If you want to add custom ca certs you could check this.

https://github.com/AzBuilder/terrakube-helm-chart#5-custom-ca-certificates-at-runtime

**Comment by Diliz** [comment]
For helm purpose (general comment- not related to the main github issue), you should use this annotation for helm charts: 
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

It will help you trigger a deployment rollout each time a related configmap (works with secrets as well) is changed (when you're frequently using helm install/upgrade it's simpler to iterate)

**Comment by alfespa17** [comment]
By the way for cors issues you could check the API logs, you should see the setup there.

It will look like this with the your domain
![image](https://user-images.githubusercontent.com/4461895/223487645-fc5c8e69-9ecc-4d7f-b0a1-bfe36c39fe59.png)

And it is taking the value from here.
https://github.com/AzBuilder/terrakube-helm-chart/blob/main/charts/terrakube/templates/secrets-api.yaml#L17

**Comment by Diliz** [comment]
I'll check this, probably an issue with only this yep, got an issue when putting my certs to the pods right now, it seems that the layers/.../jre folder is read only and the application try to put the certs I gave to him in this folder, dunno if I did something wrong here, I'm not a java dude xD

**Comment by alfespa17** [comment]
Hello @Diliz.

Let me explain you a little bit more, the terrakube componentes (api, registry and executor) are using [buildpacks](https://buildpacks.io/docs/concepts/) as you can see in this build log:

![image](https://user-images.githubusercontent.com/4461895/223739868-d206fa74-4a06-40eb-9790-db36df6ee74e.png)

When you are using buildpack to add a custom CA certificate at runtime you need to do the following:

You need to provide the following environment variable to the container:

```bash
SERVICE_BINDING_ROOT: /mnt/platform/bindings
```

If you connecto to the container you will see that inside the path there is a folder call ca-certificates
```bash
cnb@terrakube-api-678cb68d5b-ns5gt:/mnt/platform/bindings$ ls
ca-certificates
```

Inside the folder you will find your PEM CA certs and one additional file call **type**
```bash
cnb@terrakube-api-678cb68d5b-ns5gt:/mnt/platform/bindings/ca-certificates$ ls
terrakubeDemo1.pem  terrakubeDemo2.pem  type
```

If you see the content of the file called **type**

```bash
cnb@terrakube-api-678cb68d5b-ns5gt:/mnt/platform/bindings/ca-certificates$ cat type
ca-certificates
```

When you put the security.ca-secrets in your yaml the information is save inside this secret:
https://github.com/AzBuilder/terrakube-helm-chart/blob/main/charts/terrakube/templates/secrets-certs.yaml

You will see the type file with content "ca-certificates"
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-ca-secrets
type: Opaque
stringData: 
  type: |
    ca-certificates
  
  {{- with .Values.security.caCerts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
```


Finally your helm values.yaml should look something like this because where are mounting your CA certs and the file called **type** in the following path **" /mnt/platform/bindings/ca-certificates"**

```yaml
## API properties
api:
  version: "2.12.0-beta.1"
  terraformReleasesUrl: "https://eov1ys4sxa1bfy9.m.pipedream.net/"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "terrakubeDemo1.pem"
          path: "terrakubeDemo1.pem"
        - key: "terrakubeDemo2.pem"
          path: "terrakubeDemo2.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true
```

And if you go to your API pods logs you will see the following:

```bash
Added 2 additional CA certificate(s) to system truststore
Setting Active Processor Count to 2
Calculating JVM memory based on 5791152K available memory
For more information on this calculation, see https://paketo.io/docs/reference/java-reference/#memory-calculator
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx5033128K -XX:MaxMetaspaceSize=246023K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 5791152K, Thread Count: 250, Loaded Class Count: 41022, Headroom: 0%)
Enabling Java Native Memory Tracking
Adding 126 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -XX:+ExitOnOutOfMemoryError -XX:ActiveProcessorCount=2 -XX:MaxDirectMemorySize=10M -Xmx5033128K -XX:MaxMetaspaceSize=246023K -XX:ReservedCodeCacheSize=240M -Xss1M -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics -Dorg.springframework.cloud.bindings.boot.enable=true

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.8)
```

You can find how to handle ca certs when your container are usig buildpack in the following links:

* https://blog.dahanne.net/2021/02/06/customizing-cloud-native-buildpacks-practical-examples/#Add_certificates_binding_at_runtime:~:text=ca%2Dcertificates-,Add%20certificates%20binding%20at%20runtime,-If%20your%20image
* https://github.com/paketo-buildpacks/ca-certificates
* https://github.com/paketo-buildpacks/spring-boot

I hope this information can help you.

**Comment by Diliz** [comment]
Humm, I can see that my certs are taken into account with the SERVICE_BINDING_ROOT env var, but it seems that it was an issue with the libjvm at some point, do you use a version >= 1.4.0?

I clearly see the following line:
```
Added 145 additional CA certificate(s) to system truststore
...
Adding 284 container CA certificates to JVM truststore
WARNING: Unable to add container CA certificates to JVM because /layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts is read-only
```
So I'm pretty sure that the certifates are loaded since I putted them only there, it seems to be working, the only thing I think should be the culprit is the warning here, which seems related to: https://github.com/paketo-buildpacks/libjvm/releases/tag/v1.40.0 (In the enhancement section: Sets relevant paths as group-writable to support Jammy stack)

**Comment by alfespa17** [comment]
Cool nice to hear that is working for you now 👍. 

According to the logs it is using the spring boot build pack 5.23.0
```bash
2023-03-06T18:49:29.8931746Z [INFO]     [creator]     Paketo Buildpack for Spring Boot 5.23.0
2023-03-06T18:49:29.8932826Z [INFO]     [creator]       https://github.com/paketo-buildpacks/spring-boot
2023-03-06T18:49:29.8937207Z [INFO]     [creator]       Build Configuration:
2023-03-06T18:49:29.8938426Z [INFO]     [creator]         $BP_SPRING_CLOUD_BINDINGS_DISABLED   false  whether to contribute Spring Boot cloud bindings support
2023-03-06T18:49:29.8939079Z [INFO]     [creator]       Launch Configuration:
2023-03-06T18:49:29.8941931Z [INFO]     [creator]         $BPL_SPRING_CLOUD_BINDINGS_DISABLED  false  whether to auto-configure Spring Boot environment properties from bindings
2023-03-06T18:49:29.8942855Z [INFO]     [creator]         $BPL_SPRING_CLOUD_BINDINGS_ENABLED   true   Deprecated - whether to auto-configure Spring Boot environment properties from bindings
2023-03-06T18:49:30.6903545Z [INFO]     [creator]       Creating slices from layers index
2023-03-06T18:49:30.6915770Z [INFO]     [creator]         dependencies (175.3 MB)
2023-03-06T18:49:30.6922261Z [INFO]     [creator]         spring-boot-loader (281.8 KB)
2023-03-06T18:49:30.6925294Z [INFO]     [creator]         snapshot-dependencies (0.0 B)
2023-03-06T18:49:30.6951907Z [INFO]     [creator]         application (1.0 MB)
2023-03-06T18:49:30.6956718Z [INFO]     [creator]       Launch Helper: Contributing to layer
2023-03-06T18:49:30.6975251Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_spring-boot/helper/exec.d/spring-cloud-bindings
2023-03-06T18:49:30.6983213Z [INFO]     [creator]       Spring Cloud Bindings 1.11.0: Contributing to layer
2023-03-06T18:49:30.7027680Z [INFO]     [creator]         Downloading from https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-bindings/1.11.0/spring-cloud-bindings-1.11.0.jar
2023-03-06T18:49:30.7222292Z [INFO]     [creator]         Verifying checksum
2023-03-06T18:49:30.7228254Z [INFO]     [creator]         Copying to /layers/paketo-buildpacks_spring-boot/spring-cloud-bindings
2023-03-06T18:49:30.7235481Z [INFO]     [creator]       Web Application Type: Contributing to layer
2023-03-06T18:49:30.7236216Z [INFO]     [creator]         Servlet web application detected
2023-03-06T18:49:30.7237393Z [INFO]     [creator]         Writing env.launch/BPL_JVM_THREAD_COUNT.default
2023-03-06T18:49:30.7237954Z [INFO]     [creator]       4 application slices
2023-03-06T18:49:30.7238246Z [INFO]     [creator]       Image labels:
2023-03-06T18:49:30.7238693Z [INFO]     [creator]         org.opencontainers.image.title
2023-03-06T18:49:30.7239078Z [INFO]     [creator]         org.opencontainers.image.version
2023-03-06T18:49:30.7239558Z [INFO]     [creator]         org.springframework.boot.version
```

And I think it is using libjvm 1.41.0
https://github.com/paketo-buildpacks/spring-boot/blob/v5.23.0/go.mod#L11

**Comment by Diliz** [comment]
Ok found the culprit I think, it seems the api image is using a specific group/user, when trying to add certs with SERVICE_BINDING_ROOT, the certs are not added to the jvm correctly because the folder `/layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts` is read-only for a random user, dunno how it's usually done for springboot/buildpack for other apps in openshift (Only have this issue on openshift, so I think it's the main issue here)

**Comment by alfespa17** [comment]
Hello @Diliz 

There is a second option to add the ca certs at build time instead of at runtime.

Check this:
https://github.com/AzBuilder/terrakube/pull/265

There is a folder in the repository where you need to put your ca certs and just build the image following the example build script.

Maybe that approach works for you.

**Comment by alfespa17** [comment]
Hello @Diliz 

I did some changes in the buildpack builder image, now it is using ubuntu jammy, can you test maybe that fix the issue.

According the fix it was for jammy and I was using bionic.
https://github.com/paketo-buildpacks/libjvm/releases/tag/v1.40.0

```yaml
## API properties
api:
  version: "2.12.0-beta.2"
  terraformReleasesUrl: "https://eov1ys4sxa1bfy9.m.pipedream.net/"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "terrakubeDemo1.pem"
          path: "terrakubeDemo1.pem"
        - key: "terrakubeDemo2.pem"
          path: "terrakubeDemo2.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true
```

![image](https://user-images.githubusercontent.com/4461895/224084822-4cdb7cbd-8445-408d-8f6c-03dd4684a021.png)

![image](https://user-images.githubusercontent.com/4461895/224084925-2af1d9f7-2ab3-4d0b-8247-8330f603a653.png)

**Comment by Diliz** [comment]
Oh thanks! I currently added an openshift security context constraint to fix it, as I was expecting, the main culprit was the rights on the cacerts file here: /layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts

So I had to use the user 1000 in this case to make it work, which I don't really want to do for the helm chart to be installable as is in an openshift environment :/

**Comment by alfespa17** [comment]
Nice to hear that is finally working for you 👍 . 

Well at least there is an alternative to make it work in Openshift, we can add that constraint in the documentation and explain the reason. 

Terrakube basically take the dex token and check the groups inside the token to validate in which organization the use have access.

**Comment by alfespa17** [comment]
basically the group inside the token should be the name that you use inside the teams setup
https://docs.terrakube.org/user-guide/organizations/team-management

**Comment by alfespa17** [comment]
Hello @Diliz I am closing this issue, now the helm chart can work out of the box  thanks to your suggestions, feel free to open a new issue if you find any new problem
